name: Check build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  APP_ID: github-actions
  PUBLIC_KEY: github-actions
  BOT_TOKEN: github-actions
  DATABASE_URL: github-actions
  REDIS_URL: github-actions
  REDIS_TOKEN: github-actions
  RYM_BOT_USERNAME: github-actions
  RYM_BOT_PASSWORD: github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y build-essential libasound2-dev black
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
