name: Post-deploy

on: deployment_status

jobs:
  register_commands:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          if [ "${{ github.event.deployment.environment }}" == "production" ]; then
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN_PROD }}" >> $GITHUB_ENV
            echo "BASE_URL=https://rombot.vercel.app" >> $GITHUB_ENV
          else
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN_DEV }}" >> $GITHUB_ENV
            echo "BASE_URL=https://rombot-git-dev-jgchk.vercel.app" >> $GITHUB_ENV
          fi
      - name: Register commands
        run: |
          curl --fail \
          --connect-timeout 5 \
          --max-time 10 \
          --retry 5 \
          --retry-delay 0 \
          --retry-max-time 40 \
          --retry-all-errors \
          --request GET \
          --url '${{ env.BASE_URL }}/api/interactions/register?bot-token=${{ env.BOT_TOKEN }}'
  run_migrations:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          if [ "${{ github.event.deployment.environment }}" == "production" ]; then
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_DEV }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run db:push
